Closes MAIN-34
ifit/Analytics.Xamarin pull request #6
Opened 2019-05-01 18:21 UTC by charless-ifit

This pull request closes [MAIN-34](https://ifitdev.atlassian.net/browse/MAIN-34)

If for some reason there is no internet connectivity when trying to log analytics then we will cache them and try to post them again once we're connected.

2019-05-08 17:15 UTC, chrisr-ifit requested changes
Not working as expected in wolf for iOS, see https://github.com/ifit/wolf/pull/4005

2019-06-19 17:55 UTC, iFitMicahN requested changes
I get 91 builds errors on your branch for this project. I didn't get them on `master`. It sounds like what Jace ran into but he posted that on the Palantir PR not this one...

Any idea what the deal is? I'll dig in soon but thought I'd go ahead and ask.

2019-06-20 15:15 UTC, iFitMicahN commented on Analytics.Xamarin.Pcl/Client.cs
> +		public async Task<bool> Track(string userId, string eventName)
I don't think you needed to change these. Just doing `Task`->`Task<bool>` is enough, which is what you did for most of the others it looks like. I'd prefer that it matched the other so the file was consistent throughout but it isn't a huge deal.

2019-06-20 16:07 UTC, iFitMicahN approved these changes
conceding the formatting :)

2019-06-20 16:32 UTC, bendowden approved these changes

2019-06-20 21:01 UTC, merged

2019-06-20 21:02 UTC, charless-ifit commented
Merged